spring:
  config:
    import: optional:classpath:application-local.yaml

  application:
    name: FLearn_SpringBoot

  datasource:
    url: ${DB_URL:jdbc:sqlserver://localhost:1433;databaseName=FLearnDB;encrypt=true;trustServerCertificate=true;sendStringParametersAsUnicode=true}
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}

server:
  port: 8080
